<!-- ======= Start Sidebar ======= -->

  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="Index.Php">
          <i class="bi bi-grid"></i>
          <span> Dashboard </span>
        </a>
      </li>
      
      <!-- End Dashboard Nav -->

      <!-- Start Forms Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>Movie Genres </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="Add Movies Category.Php">
              <i class="bi bi-circle"></i><span> Add Movies Genres </span>
            </a>
          </li>
          <li>
            <a href="Display Category Page.Php">
              <i class="bi bi-circle"></i><span> Genre List </span>
            </a>
          </li>
         
        
          
          
        </ul>
      </li>
      
      <!-- End Forms Nav -->

       <!-- Start Tables Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="">
          <i class="bi bi-layout-text-window-reverse"></i><span> Movie Details </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
            <a href="Add Movies.Php">
              <i class="bi bi-circle"></i><span> Add Movies </span>
            </a>
          </li>
          <li>
            <a href="Display Home Movies.Php">
              <i class="bi bi-circle"></i><span> Display Movies </span>
            </a>
          </li>
         
         
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-a" data-bs-toggle="collapse" href="">
          <i class="bi bi-layout-text-window-reverse"></i><span> Theaters </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-a" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
            <a href="Add Theater.Php">
              <i class="bi bi-circle"></i><span> Add Theater </span>
            </a>
          </li>

          <li>
            <a href="Display Theater.Php">
              <i class="bi bi-circle"></i><span> Display Theater </span>
            </a>
          </li>
         
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-b" data-bs-toggle="collapse" href="">
          <i class="bi bi-layout-text-window-reverse"></i><span>Ticket details </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-b" class="nav-content collapse " data-bs-parent="#sidebar-nav">
         
        <li>
            <a href="Add Movie Ticket.Php">
              <i class="bi bi-circle"></i><span> Add Ticket Types </span>
            </a>
          </li>
          <li>
            <a href="Display Ticket Types.Php">
              <i class="bi bi-circle"></i><span> Display Ticket Types </span>
            </a>
          </li>
         
         
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-c" data-bs-toggle="collapse" href="">
          <i class="bi bi-layout-text-window-reverse"></i><span> Advertisements </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-c" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
            <a href="Add Ads.Php">
              <i class="bi bi-circle"></i><span> Add Ads </span>
            </a>
          </li>
        
            <a href="Display Ads.Php">
              <i class="bi bi-circle"></i><span> Display Ads </span>
            </a>
          </li>
         
         
        </ul>
      </li>
     
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-d" data-bs-toggle="collapse" href="">
          <i class="bi bi-layout-text-window-reverse"></i><span> Customer details </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-d" class="nav-content collapse " data-bs-parent="#sidebar-nav">
         
          <li>
            <a href="Customers.Php">
              <i class="bi bi-circle"></i><span> Customer Bookings </span>
            </a>
          </li>
          <li>
            <a href="Display Ticket Types.Php">
              <i class="bi bi-circle"></i><span> Display Ticket Types </span>
            </a>
          </li>
        
         
        </ul>
      </li>

      
      <!-- End Tables Nav -->

       <!-- Start Charts Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#charts-e" data-bs-toggle="collapse" href="#">
          <i class="bi bi-bar-chart"></i><span> Booking details </span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="charts-e" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="Admin Profile.Php">
              <i class="bi bi-circle"></i><span> Customers </span>
            </a>
          </li>
          <li>
            <a href="charts-apexcharts.html">
              <i class="bi bi-circle"></i><span>Booking Details</span>
            </a>
          </li>
        
        </ul>
      </li>
      
      <!-- End Charts Nav -->

     
      <!-- Start Profile Page Nav -->

      <li class="nav-heading">Pages</li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="Profile.Php">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li>
      
      <!-- End Profile Page Nav -->

    
      <!-- Start Register Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="Register.Php">
          <i class="bi bi-card-list"></i>
          <span> Register </span>
        </a>
      </li>
      
      <!-- End Register Page Nav -->

      <!-- Start Login Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="Login.Php">
          <i class="bi bi-box-arrow-in-right"></i>
          <span> Login </span>
        </a>
      </li>
      
      <!-- End Login Page Nav -->

    </ul>

  </aside>
  
           <!-- End Sidebar-->