<?Php
        include "Shared/_Header.Php";
 ?>    

        <!-- breadcrumb area start -->

		<section class="breadcrumb-area">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="breadcrumb-area-content">
							<h1> About Us </h1>
						</div>
					</div>
				</div>
			</div>
		</section>
		
		<!-- breadcrumb area end -->


		<!DOCTYPE html>
		<html lang="en">
		<head>
		 <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		 <link rel="stylesheet" type="text/css" href="assets/Styling/css/swiper.min.css">
		 <link href="//fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,600&display=swap"
		  rel="stylesheet">
		 
		</head>
		<body>
		<div class="w3l-ab-grids py-5">

    <div class="container py-lg-4">
	 <div class="row ab-grids-sec align-items-center">
		<div class="col-lg-6 ab-right">
			<img class="img-fluid" src="assets/images/banner1.jpg">
		</div>
		<div class="col-lg-6 ab-left pl-lg-4 mt-lg-0 mt-5">
			<h3 class="hny-title"> Movies Point Entertainment </h3>
			<p class="mt-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam id quisquam ipsam
				molestiae ad eius accusantium? Nulla dolorem perferendis inventore! posuere cubilia Curae;
				Nunc non risus in justo convallis feugiat.</p>
			<div class="ready-more mt-4">
				<a href="#" class="btn btn-primary" >Read More <span class="fa fa-angle-double-right ml-2"
						aria-hidden="true"></span></a>
			</div>
		</div>
	</div>

	<div class="container py-lg-4">
	 <div class="row ab-grids-sec align-items-center">
	 <div class="col-lg-6 ab-left pl-lg-4 mt-lg-0 mt-5">
			<h3 class="hny-title"> Movies Point Entertainment </h3>
			<p class="mt-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam id quisquam ipsam
				molestiae ad eius accusantium? Nulla dolorem perferendis inventore! posuere cubilia Curae;
				Nunc non risus in justo convallis feugiat.</p>
			<div class="ready-more mt-4">
				<a href="#" class="btn btn-primary" >Read More <span class="fa fa-angle-double-right ml-2"
						aria-hidden="true"></span></a>
			</div>
		</div>
		<div class="col-lg-6 ab-right">
			<img class="img-fluid" src="assets/images/banner1.jpg">
		</div>
		
	</div>




	

	



 </div>
 </div>
		</body>
		</html>
		






<!-- video section start -->
		
<section class="video ptb-90">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
					    <div class="section-title pb-20">
							<h1><i class="icofont icofont-film"></i> Trailers & Videos </h1>
						</div>
					</div>
				</div>
				<hr />
				<div class="row">
                    <div class="col-md-12">
						<div class="video-slider mt-20">
							<div class="video-area">
								<img src="assets/img/video/video2.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=wd7QDIIQsFA" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							<div class="video-area">
								<img src="assets/img/video/video3.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=IRsFc2gguEg" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							<div class="video-area">
								<img src="assets/img/video/video4.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=yNQPwB1NyIw" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							<div class="video-area">
								<img src="assets/img/video/video5.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=Mt1OmFL3O34" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							<div class="video-area">
								<img src="assets/img/video/video2.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=tbbveDpUZv4" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							<div class="video-area">
								<img src="assets/img/video/video3.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=CvhJnD-AHOo" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							<div class="video-area">
								<img src="assets/img/video/video4.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=Ke1Y3P9D0Bc" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							<div class="video-area">
								<img src="assets/img/video/video5.png" alt="video" />
								<a href="https://www.youtube.com/watch?v=DsdT3D_zKF0" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
						</div>
                    </div>
				</div>
			</div>
        </section>
		
		<!-- video section end -->
		
        <!-- footer section start -->
        <?Php
        include "Shared/_Footer.Php";
        ?>